name : Docker-CI
trigger:
  branches:
    include:
      - master
 
pool:
  vmImage: 'ubuntu-latest'


- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'davirangel/kong'
    command: 'build'
    Dockerfile: '**/Dockerfile'
